Class {
	#name : #MaterialDesignIconsStyle,
	#superclass : #Object,
	#category : #'OpenSmock-Iconography-Library - Material Design'
}

{ #category : #enumerating }
MaterialDesignIconsStyle class >> filled [ 

	^#filled
]

{ #category : #enumerating }
MaterialDesignIconsStyle class >> outlined [ 

	^#outlined
]

{ #category : #enumerating }
MaterialDesignIconsStyle class >> rounded [ 

	^#rounded
]

{ #category : #enumerating }
MaterialDesignIconsStyle class >> sharp [ 

	^#sharp
]

{ #category : #enumerating }
MaterialDesignIconsStyle class >> twoTone [ 

	^#twoTone
]
