Class {
	#name : #SmockTestIconsLibrary,
	#superclass : #SmockAbstractIconsLibrary,
	#category : #'OpenSmock-Iconography-Tests-Utils'
}

{ #category : #accessing }
SmockTestIconsLibrary class >> libraryName [

	^ 'Test Icons Library'
]

{ #category : #accessing }
SmockTestIconsLibrary >> rasterImageFile [ 

	^ nil
]

{ #category : #accessing }
SmockTestIconsLibrary >> vectorialImageFile [ 

	^ nil
]
